### ISSUE TITLE
[Bug]: Extra Border at last Link in the Navbar.

### ISSUE THREAD

**Issue by teju-tech** [teju-tech/Open-source-demo#1]
**Describe the bug**
Extra border to the right of the right-most Link in the navbar. 

**To Reproduce**
1. Go to landing page of the web application.
2.watch the links in the right , you will notice an extra bar in the right.
3. See error

**Expected behavior**
There should be no bar in the right of the 'Sign in' link in the navbar, so as to keep the Navbar Links section symmetrical.

**Screenshots**
![Screenshot (436)](https://github.com/user-attachments/assets/6cfb6066-52d6-401a-b919-f6fb42df2034)

**Desktop (please complete the following information):**
 - OS: [ Windows ]
 - Browser [ Brave ]
 - Version [ ]

**Smartphone (please complete the following information):**
 - Version [ 1.69.160 Chromium]

**Comment by TejasMore477** [comment]
Okay I will work on it.
